AstroNvim/docs

docs/acknowledgements.md
docs/configuration/basic_configuration.md
docs/configuration/config_options.md
docs/configuration/override_formats.md
docs/configuration/plugin_defaults.md
docs/intro.md
docs/recipes/globalstatus.md

Waiting for https://github.com/AstroNvim/AstroNvim/pull/519

New Development Branch Updates

---

docs/configuration/basic_configuration.md
docs/configuration/config_mechanism.md
docs/configuration/override_formats.md
docs/usage/mappings.md
sidebars.js

In addition to ux branch reUxlated updates, I also added short description on "Configuration mechanism" since without big picture it was hard to understand what all the detailed explanation.

Updating doc to match ux branch

---

docs/intro.md

Inspired from the following thread on discord: https://discord.com/channels/939594913560031363/1081757540322398272

docs(intro): Add LSP's to the reasons of why node is needed

---

docs/Configuration/plugin_defaults.md

This PR adds links to the respective plugins on the default plugin configurations list
resolves https://github.com/AstroNvim/astronvim.github.io/issues/76
Continuation of #77 which for some reason was unhappy

add links to default plugin configurations list

---

docs/intro.md

As we discussed on discord, please check if everything looks correct. Feel free to change anything.

Added information about community plugins

---

docs/intro.md

This is a copy of https://github.com/AstroNvim/AstroNvim/pull/2035 but for the github.io docs

Added explanation for Nerd Fonts to readme/introduction

---

docs/Recipes/advanced_lsp.md

The Astronvim community has most of these ready to go and combined with more plugins, so point to that.

Suggest Astroncommunity in LSP Specific Plugin section

---

docs/Recipes/snippets.md

Also, avoid known issue where long code lines force user to scroll horizontally in their browser.

Snippets - Refine to accommodate ~/.config/astronvim scenario

---

docs/Recipes/unattended_install.md

Finishes https://github.com/AstroNvim/astronvim.github.io/pull/63

Fix outdated unattended install command and syntax

---

docs/Configuration/override_formats.md

- `local_vim.clipboard` -> `local_vim.opt.clipboard`

chore: update override_formates.md

---

astro.config.mjs

Adds a link on each doc page to easily make edits and open new PRs

feat: add edit link to docs pages

---

src/content/docs/acknowledgements.mdx

remove mention about mini.ai as it's not using

remove mini.ai

---

src/content/docs/basic-usage/mappings.md

Add terminal mappings in mappings.md

feat: Add terminal mappings

---

src/content/docs/recipes/alpha.md

- Added a quick example on how to configure buttons on the dashboard
- Didn't specify file name as it's going to be different in v4
- Inspired by this [post in help-forum](https://discord.com/channels/939594913560031363/1192904854125936750)

docs: Customize buttons in alpha recipe

---

src/content/docs/recipes/custom_plugins.md

fix: typo in custom_plugins.md

---

src/content/docs/reference/default_plugins.mdx

fixes typo at default_plugins.mdx

(docs) fix typo at default_plugins.mdx

---

src/content/docs/recipes/snippets.mdx

It appears that the filename and headers within the luasnip documentation were recently changed, which has resulted in the previous link becoming obsolete. I have updated the link to reflect these changes. Please review the updated link to ensure it correctly points to the intended content.
Thank you for maintaining such a valuable resource, and please let me know if further adjustments are needed.
Best regards,

docs(custom snippets): fix broken link

---

src/content/docs/mappings.mdx

I had to refer back to the mappings to find this, so figure it would be good to document.

Add documentation for opening quickfix and local lists

---

src/content/docs/index.mdx

Fix small typo: lanaguages -> languages
Wasn't sure if this is a fix or a docs commit, hope it's fine like this. Just let me know if you want me to change anything :)

fix: Fix small typo in index

---

src/content/docs/faq.mdx

Hi and thanks for AstroNvim!
I'd like to offer a few small corrections to faq.mdx regarding grammar and spelling.

Minor improvements to faq.mdx
