docs/acknowledgements.md

Update link in accordance to https://github.com/AstroNvim/AstroNvim/pull/842.

update nvim-colorizer link

---

docs/intro.md

- Use `Move-Item` instead of `mv`. The "mv" command doesn't work in the command prompt, and in PowerShell, it is just an alias to `Move-Item` which can easily be overridden.
- Use `$env:LOCALAPPDATA` for neovim paths

Update Windows instructions to use idiomatic PowerShell commands

---

README.md
docs/Configuration/adding_own_plugins.md

I found myself really struggling with the current documentation (after having used AstroVim briefly last year) and coming back to it, trying to remember how to install my own plugins. I think the lack of a clear entry about this over made it difficult to pick apart what was required.
This might be too basic, or require some re-wording but I was almost ready to throw in the towel myself, and think it would be a shame to lose new users who give up too quickly looking for this info. Hope it's of some minor use.
(Also added a clarifying remark about a gotcha I had while running these docs locally)
@mehalter I'm not sure if you get a notification when I create these, but I can't assign anyone so tagging you on this first one to find out (working on another PR)

Added an entry about installing ones own plugins

---

docs/Recipes/alpha.md

Added wins var.
Added if else to check if window count > 1.
if then also calls vim.cmd[[silent only]] when closing the last buffer.
else functions as before changes.
To recreate the bug, enable alpha_on_bye and then open splits and close all buffers when closing the last buffer all splits will attempt alpha_on_bye, and error messages appear in the command line. It then becomes difficult to close all the windows, and the best solution is to restart the session.

Fixed bug where alpha_on_bye would error if windows were open when you closed the last buffer.

---

docs/Configuration/config_mechanism.md

I accidentally deleted "by" in the original commit.  When I read again, I felt odd.  Now here is the fix for the missing "by".  With this added, split and single configuration explanation is completely in sync.
Signed-off-by: Osamu Aoki <osamu@debian.org>

Add missing "by"

---

docs/Recipes/disable_tabline.md

Fixed small typo. I suppose it could also be trying to say tables but I think this is correct.

Fixed typo in disable_tabline.md in docs/Recipes/disable_tabline.md

---

docs/Recipes/cmp.md
docs/Recipes/disable_tabline.md

Fixed a few typos in Recipes/cmp.md where autopairs was mentioned in comments instead of nvim-cmp.
this is ontop of my previous commit, also fixing typos.

Fixed more typos in Recipes/cmp.md

---

docs/Recipes/colorscheme.md
docs/Recipes/custom_plugins.md

Fix typos that were using the old packer.nvim field names (`as`) to use the lazy.nvim names (`name`)

Fix typos in colorscheme.md and custom_plugins.md

---

docs/Basic Usage/mappings.md

While I did not use the LSP type definition, definition, and implementation functions hotkeys yet, the references function, which supposedly searches through the code base to find lines that uses said function or class is not actually triggered by `gr`, but instead `lR`. Maybe the documentation is out of sync with the code changes?
Sorry for the small PR, as I do not understand those other functions enough to propose changes.

LSP references search hotkey documentation error?

---

versioned_docs/version-3.29.0/Basic Usage/walkthough.md

pressing `space+D` deletes the line the cursor is currently on, while `space+d` actually brings up the debugger menu.
Hopefully this simple PR is not too much trouble.

debugger shortcut mistake

---

docs/intro.md

Closes #109
- Fix link rendering for home page
- Fix link location for terminal emulators
See: Fixed renders, link to terminal emulator goes to new repo

fix(docs): adjust links to render

---

src/content/docs/basic-usage/mappings.md

There's only one entry with `shift`, and it's this one. Use the uppercase directly as the rest of bindings shown.
Easier to find.

chore: Change `shift + k` for `K`

---

src/content/docs/recipes/colorscheme.mdx

The docs for setting colorscheme says to update the astrocore plugin but actually we need to set the astroui plugin

fix: docs for setting colorscheme is incorrect

---

src/content/docs/mappings.mdx

Fix the mappings listed for `Previous completion`.

fix(mappings): correct prev completion mappings

---

src/content/docs/reference/alt_install.mdx

fix(reference): remove unnecessary backtick from the clone commands

---

src/content/docs/mappings.mdx

This removes the repeated mappings for `Next snippet location` and `Previous snippet location` leaving the ones on lines 70-71.

fix(mappings): remove repeated snippet nav mappings

---

src/content/docs/configuration/manage_user_config.mdx

The docs indicates `~/.config/nvim/lua` as the path to clone the user config into. But it seems the correct path is `~/.config/nvim`.

Fix typo in user config path

---

src/content/docs/recipes/alpha.mdx

With `.start(true)` Alpha dashboard never get opened on last buffer close.

docs: fix example with open alpha on last buffer close

---

src/content/docs/configuration/customizing_plugins.mdx

One of the examples in the documentation seems to be wrong: if I understand it correctly, the function is supposed to add an `indent` field, but it doesn't appear in the final resolved config. Probably a copy-paste error.

fix(customizing_plugins): example resolution in customizing_plugins.mdx

---

src/content/docs/recipes/mappings.mdx

This fixes a small typo in this [part](https://docs.astronvim.com/recipes/mappings/#enable-telescope-lsp-mappings) of the docs.

fix(mappings): fix typo

---

src/content/docs/index.mdx

it looks like with the release of 4.0, AstroUpdatePackages was removed and AstroUpdate does the same thing (it calls astrocore and updates everything)

doc: update the update command

---

src/content/docs/mappings.mdx

As of AstroNvim v4.23.0, the default direction for terminals was changed to `horizontal`. This PR updates the `mappings` page of the docs with the new information.

Fix: invalid mapping for floating terminal

---

src/content/docs/recipes/snippets.mdx

Small update to the guide on creating snippets.
- note that a vue file must have a .vue extension. Seems a little silly but I wasted 5-10 min before realizing it.
> Feel free to reject if you think it is too trivial.

docs: Note File Type in Snippet Guide

---

src/content/docs/recipes/cmp.mdx

This adds a section on how to adjust cmp to limit it's size. To solve an issue like this: https://github.com/hrsh7th/nvim-cmp/issues/1154#issuecomment-1872926479

docs: add section to adjust cmp label and menu length

---

src/content/docs/configuration/manage_user_config.mdx

Fix typo in "Managing User Configuraton"

---

.envrc
.gitignore
.tool-versions
flake.lock
flake.nix

- Flake.nix and lock for devShell
- .envrc for direnv
- Ignore .direnv folder

feat(build): Add in nix flake for devShell

---

src/content/docs/recipes/advanced_lsp.mdx

Replace [rust-tools](https://github.com/simrat39/rust-tools.nvim) with [rustaceanvim](https://github.com/mrcjkb/rustaceanvim).
The `rust-tools` repo is now archived. `rustaceanvim` is a maintained fork of `rust-tools`.
The [Astrocommunity Rust language pack](https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/pack/rust) has also migrated to `rustaceanvim`.

Replace `rust-tools` with `rustaceanvim`

---

src/content/docs/recipes/ai.mdx

Add a recipe page for setting up and configuring AI completion plugins

feat(recipes): start working on an AI recipes section

---

src/content/docs/recipes/rooter.mdx

A small summary to help explain what is a rooter and how it can be used. Feel free to correct or tell me to change any parts :slightly_smiling_face:

feat(recipes): add additional information about rooter

---

src/content/docs/recipes/ai.mdx

In the AI guide, is mentions that `nvim-cmp` is the default completion plugin, but in the "Customize cmp completion" guide it says `blink.cmp` is the default one. This fix updates the AI doc to match the completion one.

fix(ai): blink.cmp should be default completion plugin

---

src/content/docs/index.mdx

Fix broken link, treesitter refactored the repo

fix: broken link for treesitter-cli

---

src/content/docs/configuration/customizing_plugins.mdx

I improved the sentence structure of one of the paragraphs in [How `opts` Overriding Works](https://docs.astronvim.com/configuration/customizing_plugins/#how-opts-overriding-works) to make it easier to read, and clarified what the user needs to pay attention to. I kept the related example the same, since it still fits.

docs(customizing plugins): clarify nested key behavior when using function notation
